// Generated by rstantools.  Do not edit by hand.

/*
    StanMoMo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    StanMoMo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with StanMoMo.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_M6model_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_M6model");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
    reader.add_event(144, 142, "end", "model_M6model");
    return reader;
}
#include <stan_meta_header.hpp>
class model_M6model : public prob_grad {
=======
    reader.add_event(123, 121, "end", "model_M6model");
    return reader;
}
#include <stan_meta_header.hpp>
class model_M6model
  : public stan::model::model_base_crtp<model_M6model> {
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
private:
        int J;
        int T;
        std::vector<int> d;
        vector_d e;
        vector_d age;
        int Tfor;
        int Tval;
        std::vector<int> dval;
        vector_d eval;
        int family;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        vector_d index;
=======
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        vector_d offset;
        vector_d offset2;
        int C;
        int L;
public:
    model_M6model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_M6model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_M6model_namespace::model_M6model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "J", "int", context__.to_vec());
            J = int(0);
            vals_i__ = context__.vals_i("J");
            pos__ = 0;
            J = vals_i__[pos__++];
            check_greater_or_equal(function__, "J", J, 1);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 1);
            current_statement_begin__ = 6;
            validate_non_negative_index("d", "(J * T)", (J * T));
            context__.validate_dims("data initialization", "d", "int", context__.to_vec((J * T)));
            d = std::vector<int>((J * T), int(0));
            vals_i__ = context__.vals_i("d");
            pos__ = 0;
            size_t d_k_0_max__ = (J * T);
            for (size_t k_0__ = 0; k_0__ < d_k_0_max__; ++k_0__) {
                d[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 7;
            validate_non_negative_index("e", "(J * T)", (J * T));
            context__.validate_dims("data initialization", "e", "vector_d", context__.to_vec((J * T)));
            e = Eigen::Matrix<double, Eigen::Dynamic, 1>((J * T));
            vals_r__ = context__.vals_r("e");
            pos__ = 0;
            size_t e_j_1_max__ = (J * T);
            for (size_t j_1__ = 0; j_1__ < e_j_1_max__; ++j_1__) {
                e(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("age", "J", J);
            context__.validate_dims("data initialization", "age", "vector_d", context__.to_vec(J));
            age = Eigen::Matrix<double, Eigen::Dynamic, 1>(J);
            vals_r__ = context__.vals_r("age");
            pos__ = 0;
            size_t age_j_1_max__ = J;
            for (size_t j_1__ = 0; j_1__ < age_j_1_max__; ++j_1__) {
                age(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "Tfor", "int", context__.to_vec());
            Tfor = int(0);
            vals_i__ = context__.vals_i("Tfor");
            pos__ = 0;
            Tfor = vals_i__[pos__++];
            check_greater_or_equal(function__, "Tfor", Tfor, 1);
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "Tval", "int", context__.to_vec());
            Tval = int(0);
            vals_i__ = context__.vals_i("Tval");
            pos__ = 0;
            Tval = vals_i__[pos__++];
            check_greater_or_equal(function__, "Tval", Tval, 0);
            current_statement_begin__ = 11;
            validate_non_negative_index("dval", "(J * Tval)", (J * Tval));
            context__.validate_dims("data initialization", "dval", "int", context__.to_vec((J * Tval)));
            dval = std::vector<int>((J * Tval), int(0));
            vals_i__ = context__.vals_i("dval");
            pos__ = 0;
            size_t dval_k_0_max__ = (J * Tval);
            for (size_t k_0__ = 0; k_0__ < dval_k_0_max__; ++k_0__) {
                dval[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("eval", "(J * Tval)", (J * Tval));
            context__.validate_dims("data initialization", "eval", "vector_d", context__.to_vec((J * Tval)));
            eval = Eigen::Matrix<double, Eigen::Dynamic, 1>((J * Tval));
            vals_r__ = context__.vals_r("eval");
            pos__ = 0;
            size_t eval_j_1_max__ = (J * Tval);
            for (size_t j_1__ = 0; j_1__ < eval_j_1_max__; ++j_1__) {
                eval(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "family", "int", context__.to_vec());
            family = int(0);
            vals_i__ = context__.vals_i("family");
            pos__ = 0;
            family = vals_i__[pos__++];
            check_greater_or_equal(function__, "family", family, 0);
            check_less_or_equal(function__, "family", family, 1);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 14;
            validate_non_negative_index("index", "(T - 1)", (T - 1));
            context__.validate_dims("data initialization", "index", "vector_d", context__.to_vec((T - 1)));
            index = Eigen::Matrix<double, Eigen::Dynamic, 1>((T - 1));
            vals_r__ = context__.vals_r("index");
            pos__ = 0;
            size_t index_j_1_max__ = (T - 1);
            for (size_t j_1__ = 0; j_1__ < index_j_1_max__; ++j_1__) {
                index(j_1__) = vals_r__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 17;
=======
            // initialize transformed data variables
            current_statement_begin__ = 16;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("offset", "(J * T)", (J * T));
            offset = Eigen::Matrix<double, Eigen::Dynamic, 1>((J * T));
            stan::math::fill(offset, DUMMY_VAR__);
            stan::math::assign(offset,stan::math::log(e));
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 18;
=======
            current_statement_begin__ = 17;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("offset2", "(J * Tval)", (J * Tval));
            offset2 = Eigen::Matrix<double, Eigen::Dynamic, 1>((J * Tval));
            stan::math::fill(offset2, DUMMY_VAR__);
            stan::math::assign(offset2,stan::math::log(eval));
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 19;
            C = int(0);
            stan::math::fill(C, std::numeric_limits<int>::min());
            current_statement_begin__ = 20;
            L = int(0);
            stan::math::fill(L, std::numeric_limits<int>::min());
            // execute transformed data statements
            current_statement_begin__ = 21;
            stan::math::assign(C, ((J + T) - 1));
            current_statement_begin__ = 22;
            stan::math::assign(L, (J * Tfor));
            // validate transformed data
            current_statement_begin__ = 19;
            check_greater_or_equal(function__, "C", C, 1);
            current_statement_begin__ = 20;
=======
            current_statement_begin__ = 18;
            C = int(0);
            stan::math::fill(C, std::numeric_limits<int>::min());
            current_statement_begin__ = 19;
            L = int(0);
            stan::math::fill(L, std::numeric_limits<int>::min());
            // execute transformed data statements
            current_statement_begin__ = 20;
            stan::math::assign(C, ((J + T) - 1));
            current_statement_begin__ = 21;
            stan::math::assign(L, (J * Tfor));
            // validate transformed data
            current_statement_begin__ = 18;
            check_greater_or_equal(function__, "C", C, 1);
            current_statement_begin__ = 19;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            check_greater_or_equal(function__, "L", L, 1);
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 25;
            validate_non_negative_index("aux", "logical_gt(family, 0)", logical_gt(family, 0));
            num_params_r__ += (1 * logical_gt(family, 0));
            current_statement_begin__ = 26;
            validate_non_negative_index("alpha", "3", 3);
            num_params_r__ += 3;
            current_statement_begin__ = 27;
            validate_non_negative_index("alpha2", "3", 3);
            num_params_r__ += 3;
            current_statement_begin__ = 28;
            validate_non_negative_index("sigma", "3", 3);
            num_params_r__ += (1 * 3);
            current_statement_begin__ = 29;
            validate_non_negative_index("k", "T", T);
            num_params_r__ += T;
            current_statement_begin__ = 30;
=======
            current_statement_begin__ = 24;
            validate_non_negative_index("aux", "logical_gt(family, 0)", logical_gt(family, 0));
            num_params_r__ += (1 * logical_gt(family, 0));
            current_statement_begin__ = 25;
            num_params_r__ += 1;
            current_statement_begin__ = 26;
            num_params_r__ += 1;
            current_statement_begin__ = 27;
            validate_non_negative_index("sigma", "3", 3);
            num_params_r__ += (1 * 3);
            current_statement_begin__ = 28;
            validate_non_negative_index("k", "T", T);
            num_params_r__ += T;
            current_statement_begin__ = 29;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("k2", "T", T);
            num_params_r__ += T;
            current_statement_begin__ = 31;
            num_params_r__ += 1;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 33;
            num_params_r__ += 1;
            current_statement_begin__ = 34;
            num_params_r__ += 1;
            current_statement_begin__ = 35;
=======
            current_statement_begin__ = 32;
            num_params_r__ += 1;
            current_statement_begin__ = 33;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("gs", "(C - 2)", (C - 2));
            num_params_r__ += (C - 2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_M6model() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 25;
=======
        current_statement_begin__ = 24;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("aux")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aux missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aux");
        pos__ = 0U;
        validate_non_negative_index("aux", "logical_gt(family, 0)", logical_gt(family, 0));
        context__.validate_dims("parameter initialization", "aux", "double", context__.to_vec(logical_gt(family, 0)));
        std::vector<double> aux(logical_gt(family, 0), double(0));
        size_t aux_k_0_max__ = logical_gt(family, 0);
        for (size_t k_0__ = 0; k_0__ < aux_k_0_max__; ++k_0__) {
            aux[k_0__] = vals_r__[pos__++];
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        }
        size_t aux_i_0_max__ = logical_gt(family, 0);
        for (size_t i_0__ = 0; i_0__ < aux_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, aux[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 26;
=======
        }
        size_t aux_i_0_max__ = logical_gt(family, 0);
        for (size_t i_0__ = 0; i_0__ < aux_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0.1, aux[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 25;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "3", 3);
        context__.validate_dims("parameter initialization", "alpha", "vector_d", context__.to_vec(3));
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha(3);
        size_t alpha_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            alpha(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 27;
=======
        current_statement_begin__ = 26;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("alpha2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha2");
        pos__ = 0U;
        validate_non_negative_index("alpha2", "3", 3);
        context__.validate_dims("parameter initialization", "alpha2", "vector_d", context__.to_vec(3));
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha2(3);
        size_t alpha2_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha2_j_1_max__; ++j_1__) {
            alpha2(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(alpha2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 28;
=======
        current_statement_begin__ = 27;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        validate_non_negative_index("sigma", "3", 3);
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec(3));
        std::vector<double> sigma(3, double(0));
        size_t sigma_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            sigma[k_0__] = vals_r__[pos__++];
        }
        size_t sigma_i_0_max__ = 3;
        for (size_t i_0__ = 0; i_0__ < sigma_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, sigma[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 29;
=======
        current_statement_begin__ = 28;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("k")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable k missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("k");
        pos__ = 0U;
        validate_non_negative_index("k", "T", T);
        context__.validate_dims("parameter initialization", "k", "vector_d", context__.to_vec(T));
        Eigen::Matrix<double, Eigen::Dynamic, 1> k(T);
        size_t k_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k_j_1_max__; ++j_1__) {
            k(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(k);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable k: ") + e.what()), current_statement_begin__, prog_reader__());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 30;
=======
        current_statement_begin__ = 29;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("k2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable k2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("k2");
        pos__ = 0U;
        validate_non_negative_index("k2", "T", T);
        context__.validate_dims("parameter initialization", "k2", "vector_d", context__.to_vec(T));
        Eigen::Matrix<double, Eigen::Dynamic, 1> k2(T);
        size_t k2_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k2_j_1_max__; ++j_1__) {
            k2(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(k2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable k2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 31;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        if (!(context__.contains_r("rho")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable rho missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("rho");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "rho", "double", context__.to_vec());
        double rho(0);
        rho = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(-(1), 1, rho);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable rho: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 33;
=======
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("psi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable psi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("psi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "psi", "double", context__.to_vec());
        double psi(0);
        psi = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(psi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable psi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 34;
=======
        current_statement_begin__ = 32;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("psi2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable psi2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("psi2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "psi2", "double", context__.to_vec());
        double psi2(0);
        psi2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(psi2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable psi2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        current_statement_begin__ = 35;
=======
        current_statement_begin__ = 33;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        if (!(context__.contains_r("gs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable gs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("gs");
        pos__ = 0U;
        validate_non_negative_index("gs", "(C - 2)", (C - 2));
        context__.validate_dims("parameter initialization", "gs", "vector_d", context__.to_vec((C - 2)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> gs((C - 2));
        size_t gs_j_1_max__ = (C - 2);
        for (size_t j_1__ = 0; j_1__ < gs_j_1_max__; ++j_1__) {
            gs(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(gs);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable gs: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 25;
=======
            current_statement_begin__ = 24;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            std::vector<local_scalar_t__> aux;
            size_t aux_d_0_max__ = logical_gt(family, 0);
            aux.reserve(aux_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < aux_d_0_max__; ++d_0__) {
                if (jacobian__)
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                    aux.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    aux.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 26;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> alpha;
=======
                    aux.push_back(in__.scalar_lb_constrain(0.1, lp__));
                else
                    aux.push_back(in__.scalar_lb_constrain(0.1));
            }
            current_statement_begin__ = 25;
            local_scalar_t__ alpha;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.vector_constrain(3, lp__);
            else
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                alpha = in__.vector_constrain(3);
            current_statement_begin__ = 27;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> alpha2;
=======
                alpha = in__.scalar_constrain();
            current_statement_begin__ = 26;
            local_scalar_t__ alpha2;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            (void) alpha2;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha2 = in__.vector_constrain(3, lp__);
            else
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                alpha2 = in__.vector_constrain(3);
            current_statement_begin__ = 28;
=======
                alpha2 = in__.scalar_constrain();
            current_statement_begin__ = 27;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            std::vector<local_scalar_t__> sigma;
            size_t sigma_d_0_max__ = 3;
            sigma.reserve(sigma_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < sigma_d_0_max__; ++d_0__) {
                if (jacobian__)
                    sigma.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    sigma.push_back(in__.scalar_lb_constrain(0));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 29;
=======
            current_statement_begin__ = 28;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> k;
            (void) k;  // dummy to suppress unused var warning
            if (jacobian__)
                k = in__.vector_constrain(T, lp__);
            else
                k = in__.vector_constrain(T);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 30;
=======
            current_statement_begin__ = 29;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> k2;
            (void) k2;  // dummy to suppress unused var warning
            if (jacobian__)
                k2 = in__.vector_constrain(T, lp__);
            else
                k2 = in__.vector_constrain(T);
            current_statement_begin__ = 31;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            local_scalar_t__ rho;
            (void) rho;  // dummy to suppress unused var warning
            if (jacobian__)
                rho = in__.scalar_lub_constrain(-(1), 1, lp__);
            else
                rho = in__.scalar_lub_constrain(-(1), 1);
            current_statement_begin__ = 33;
=======
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            local_scalar_t__ psi;
            (void) psi;  // dummy to suppress unused var warning
            if (jacobian__)
                psi = in__.scalar_constrain(lp__);
            else
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                psi = in__.scalar_constrain();
            current_statement_begin__ = 34;
=======
                psi = in__.scalar_lub_constrain(-(1), 1);
            current_statement_begin__ = 32;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            local_scalar_t__ psi2;
            (void) psi2;  // dummy to suppress unused var warning
            if (jacobian__)
                psi2 = in__.scalar_constrain(lp__);
            else
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                psi2 = in__.scalar_constrain();
            current_statement_begin__ = 35;
=======
                psi2 = in__.scalar_lub_constrain(-(1), 1);
            current_statement_begin__ = 33;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> gs;
            (void) gs;  // dummy to suppress unused var warning
            if (jacobian__)
                gs = in__.vector_constrain((C - 2), lp__);
            else
                gs = in__.vector_constrain((C - 2));
            // transformed parameters
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 39;
=======
            current_statement_begin__ = 37;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("g", "C", C);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> g(C);
            stan::math::initialize(g, DUMMY_VAR__);
            stan::math::fill(g, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 40;
=======
            current_statement_begin__ = 38;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi, DUMMY_VAR__);
            stan::math::assign(phi,stan::math::negative_infinity());
            // transformed parameters block statements
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 41;
            if (as_bool(logical_gt(family, 0))) {
                current_statement_begin__ = 41;
                stan::math::assign(phi, inv(get_base1(aux, 1, "aux", 1)));
            }
            current_statement_begin__ = 42;
=======
            current_statement_begin__ = 39;
            if (as_bool(logical_gt(family, 0))) {
                current_statement_begin__ = 39;
                stan::math::assign(phi, get_base1(aux, 1, "aux", 1));
            }
            current_statement_begin__ = 40;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable g");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 43;
=======
            current_statement_begin__ = 41;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_min_max(2, (C - 1)), stan::model::nil_index_list()), 
                        gs, 
                        "assigning variable g");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 44;
=======
            current_statement_begin__ = 42;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_uni(C), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable g");
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 39;
=======
            current_statement_begin__ = 37;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t g_j_1_max__ = C;
            for (size_t j_1__ = 0; j_1__ < g_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(g(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: g" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable g: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 40;
=======
            current_statement_begin__ = 38;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            if (stan::math::is_uninitialized(phi)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: phi";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable phi: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            // model body
            {
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 48;
=======
            current_statement_begin__ = 46;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("mu", "(J * T)", (J * T));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mu((J * T));
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 49;
=======
            current_statement_begin__ = 47;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            int pos(0);
            (void) pos;  // dummy to suppress unused var warning
            stan::math::fill(pos, std::numeric_limits<int>::min());
            stan::math::assign(pos,1);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 50;
            for (int t = 1; t <= T; ++t) {
                current_statement_begin__ = 50;
                for (int x = 1; x <= J; ++x) {
                    current_statement_begin__ = 51;
=======
            current_statement_begin__ = 48;
            for (int t = 1; t <= T; ++t) {
                current_statement_begin__ = 48;
                for (int x = 1; x <= J; ++x) {
                    current_statement_begin__ = 49;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                    stan::model::assign(mu, 
                                stan::model::cons_list(stan::model::index_uni(pos), stan::model::nil_index_list()), 
                                (((get_base1(offset, pos, "offset", 1) + get_base1(k, t, "k", 1)) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2, t, "k2", 1))) + get_base1(g, ((t - x) + J), "g", 1)), 
                                "assigning variable mu");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                    current_statement_begin__ = 52;
                    stan::math::assign(pos, (pos + 1));
                }
            }
            current_statement_begin__ = 55;
            lp_accum__.add(normal_log(get_base1(k, 1, "k", 1), (get_base1(alpha, 1, "alpha", 1) + get_base1(alpha, 2, "alpha", 1)), stan::math::sqrt(10)));
            current_statement_begin__ = 56;
            lp_accum__.add(normal_log(get_base1(k2, 1, "k2", 1), (get_base1(alpha2, 1, "alpha2", 1) + get_base1(alpha2, 2, "alpha2", 1)), stan::math::sqrt(10)));
            current_statement_begin__ = 58;
            lp_accum__.add(normal_log(stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(2, T), stan::model::nil_index_list()), "k"), add(add(get_base1(alpha, 1, "alpha", 1), multiply(get_base1(alpha, 2, "alpha", 1), index)), multiply(get_base1(alpha, 3, "alpha", 1), stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(1, (T - 1)), stan::model::nil_index_list()), "k"))), get_base1(sigma, 1, "sigma", 1)));
            current_statement_begin__ = 60;
            lp_accum__.add(normal_log(stan::model::rvalue(k2, stan::model::cons_list(stan::model::index_min_max(2, T), stan::model::nil_index_list()), "k2"), add(add(add(get_base1(alpha2, 1, "alpha2", 1), multiply(get_base1(alpha2, 2, "alpha2", 1), index)), multiply(get_base1(alpha2, 3, "alpha2", 1), stan::model::rvalue(k2, stan::model::cons_list(stan::model::index_min_max(1, (T - 1)), stan::model::nil_index_list()), "k2"))), multiply(((rho * get_base1(sigma, 2, "sigma", 1)) / get_base1(sigma, 1, "sigma", 1)), subtract(stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(2, T), stan::model::nil_index_list()), "k"), add(add(get_base1(alpha, 1, "alpha", 1), multiply(get_base1(alpha, 2, "alpha", 1), index)), multiply(get_base1(alpha, 3, "alpha", 1), stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(1, (T - 1)), stan::model::nil_index_list()), "k")))))), (get_base1(sigma, 2, "sigma", 1) * stan::math::sqrt((1 - square(rho))))));
            current_statement_begin__ = 64;
            lp_accum__.add(normal_log(get_base1(gs, 1, "gs", 1), 0, get_base1(sigma, 3, "sigma", 1)));
            current_statement_begin__ = 65;
            lp_accum__.add(normal_log(get_base1(gs, 2, "gs", 1), ((psi + psi2) * get_base1(gs, 1, "gs", 1)), get_base1(sigma, 3, "sigma", 1)));
            current_statement_begin__ = 66;
            lp_accum__.add(normal_log(stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(3, (C - 2)), stan::model::nil_index_list()), "gs"), subtract(multiply((psi + psi2), stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(2, (C - 3)), stan::model::nil_index_list()), "gs")), multiply((psi * psi2), stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(1, (C - 4)), stan::model::nil_index_list()), "gs"))), get_base1(sigma, 3, "sigma", 1)));
            current_statement_begin__ = 68;
            if (as_bool(logical_eq(family, 0))) {
                current_statement_begin__ = 69;
                lp_accum__.add(poisson_log_log(d, mu));
            } else {
                current_statement_begin__ = 72;
                lp_accum__.add(neg_binomial_2_log_log(d, mu, phi));
            }
            current_statement_begin__ = 74;
            lp_accum__.add(exponential_log(sigma, 0.1));
            current_statement_begin__ = 75;
            lp_accum__.add(normal_log(alpha, 0, stan::math::sqrt(10)));
            current_statement_begin__ = 76;
            lp_accum__.add(normal_log(alpha2, 0, stan::math::sqrt(10)));
            current_statement_begin__ = 77;
            lp_accum__.add(normal_log(psi, 0, stan::math::sqrt(10)));
            current_statement_begin__ = 78;
            lp_accum__.add(normal_log(psi2, 0, stan::math::sqrt(10)));
            current_statement_begin__ = 79;
            if (as_bool(logical_gt(family, 0))) {
                current_statement_begin__ = 79;
                lp_accum__.add(normal_log(aux, 0, 10));
            }
=======
                    current_statement_begin__ = 50;
                    stan::math::assign(pos, (pos + 1));
                }
            }
            current_statement_begin__ = 53;
            lp_accum__.add(normal_log<propto__>(get_base1(k, 1, "k", 1), -(3), 1));
            current_statement_begin__ = 54;
            lp_accum__.add(normal_log<propto__>(stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(2, T), stan::model::nil_index_list()), "k"), add(alpha, stan::model::rvalue(k, stan::model::cons_list(stan::model::index_min_max(1, (T - 1)), stan::model::nil_index_list()), "k")), get_base1(sigma, 1, "sigma", 1)));
            current_statement_begin__ = 55;
            lp_accum__.add(normal_log<propto__>(get_base1(k2, 1, "k2", 1), 0, 1));
            current_statement_begin__ = 56;
            lp_accum__.add(normal_log<propto__>(stan::model::rvalue(k2, stan::model::cons_list(stan::model::index_min_max(2, T), stan::model::nil_index_list()), "k2"), add(alpha2, stan::model::rvalue(k2, stan::model::cons_list(stan::model::index_min_max(1, (T - 1)), stan::model::nil_index_list()), "k2")), get_base1(sigma, 2, "sigma", 1)));
            current_statement_begin__ = 57;
            lp_accum__.add(normal_log<propto__>(get_base1(gs, 1, "gs", 1), 0, 1));
            current_statement_begin__ = 58;
            lp_accum__.add(normal_log<propto__>(get_base1(gs, 2, "gs", 1), ((psi + psi2) * get_base1(gs, 1, "gs", 1)), get_base1(sigma, 2, "sigma", 1)));
            current_statement_begin__ = 59;
            lp_accum__.add(normal_log<propto__>(stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(3, (C - 2)), stan::model::nil_index_list()), "gs"), subtract(multiply((psi + psi2), stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(2, (C - 3)), stan::model::nil_index_list()), "gs")), multiply((psi * psi2), stan::model::rvalue(gs, stan::model::cons_list(stan::model::index_min_max(1, (C - 4)), stan::model::nil_index_list()), "gs"))), get_base1(sigma, 2, "sigma", 1)));
            current_statement_begin__ = 60;
            if (as_bool(logical_eq(family, 0))) {
                current_statement_begin__ = 61;
                lp_accum__.add(poisson_log_log(d, mu));
            } else {
                current_statement_begin__ = 64;
                lp_accum__.add(neg_binomial_2_log_log(d, mu, phi));
            }
            current_statement_begin__ = 66;
            lp_accum__.add(exponential_log(get_base1(sigma, 3, "sigma", 1), 1));
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("aux");
        names__.push_back("alpha");
        names__.push_back("alpha2");
        names__.push_back("sigma");
        names__.push_back("k");
        names__.push_back("k2");
        names__.push_back("rho");
        names__.push_back("psi");
        names__.push_back("psi2");
        names__.push_back("gs");
        names__.push_back("g");
        names__.push_back("phi");
        names__.push_back("k_p");
        names__.push_back("k2_p");
        names__.push_back("g_p");
        names__.push_back("gf");
        names__.push_back("mufor");
        names__.push_back("log_lik");
        names__.push_back("log_lik2");
        names__.push_back("pos");
        names__.push_back("pos2");
        names__.push_back("pos3");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(logical_gt(family, 0));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(T);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(T);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((C - 2));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(C);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Tfor);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Tfor);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Tfor);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((C + Tfor));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(L);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((J * T));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((J * Tval));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_M6model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> aux;
        size_t aux_d_0_max__ = logical_gt(family, 0);
        aux.reserve(aux_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < aux_d_0_max__; ++d_0__) {
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            aux.push_back(in__.scalar_lb_constrain(0));
=======
            aux.push_back(in__.scalar_lb_constrain(0.1));
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        }
        size_t aux_k_0_max__ = logical_gt(family, 0);
        for (size_t k_0__ = 0; k_0__ < aux_k_0_max__; ++k_0__) {
            vars__.push_back(aux[k_0__]);
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha = in__.vector_constrain(3);
        size_t alpha_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            vars__.push_back(alpha(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha2 = in__.vector_constrain(3);
        size_t alpha2_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha2_j_1_max__; ++j_1__) {
            vars__.push_back(alpha2(j_1__));
        }
=======
        double alpha = in__.scalar_constrain();
        vars__.push_back(alpha);
        double alpha2 = in__.scalar_constrain();
        vars__.push_back(alpha2);
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        std::vector<double> sigma;
        size_t sigma_d_0_max__ = 3;
        sigma.reserve(sigma_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < sigma_d_0_max__; ++d_0__) {
            sigma.push_back(in__.scalar_lb_constrain(0));
        }
        size_t sigma_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            vars__.push_back(sigma[k_0__]);
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> k = in__.vector_constrain(T);
        size_t k_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k_j_1_max__; ++j_1__) {
            vars__.push_back(k(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> k2 = in__.vector_constrain(T);
        size_t k2_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k2_j_1_max__; ++j_1__) {
            vars__.push_back(k2(j_1__));
        }
        double rho = in__.scalar_lub_constrain(-(1), 1);
        vars__.push_back(rho);
        double psi = in__.scalar_constrain();
        vars__.push_back(psi);
        double psi2 = in__.scalar_constrain();
        vars__.push_back(psi2);
        Eigen::Matrix<double, Eigen::Dynamic, 1> gs = in__.vector_constrain((C - 2));
        size_t gs_j_1_max__ = (C - 2);
        for (size_t j_1__ = 0; j_1__ < gs_j_1_max__; ++j_1__) {
            vars__.push_back(gs(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 39;
=======
            current_statement_begin__ = 37;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("g", "C", C);
            Eigen::Matrix<double, Eigen::Dynamic, 1> g(C);
            stan::math::initialize(g, DUMMY_VAR__);
            stan::math::fill(g, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 40;
=======
            current_statement_begin__ = 38;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            double phi;
            (void) phi;  // dummy to suppress unused var warning
            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi, DUMMY_VAR__);
            stan::math::assign(phi,stan::math::negative_infinity());
            // do transformed parameters statements
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 41;
            if (as_bool(logical_gt(family, 0))) {
                current_statement_begin__ = 41;
                stan::math::assign(phi, inv(get_base1(aux, 1, "aux", 1)));
            }
            current_statement_begin__ = 42;
=======
            current_statement_begin__ = 39;
            if (as_bool(logical_gt(family, 0))) {
                current_statement_begin__ = 39;
                stan::math::assign(phi, get_base1(aux, 1, "aux", 1));
            }
            current_statement_begin__ = 40;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable g");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 43;
=======
            current_statement_begin__ = 41;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_min_max(2, (C - 1)), stan::model::nil_index_list()), 
                        gs, 
                        "assigning variable g");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 44;
=======
            current_statement_begin__ = 42;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g, 
                        stan::model::cons_list(stan::model::index_uni(C), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable g");
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t g_j_1_max__ = C;
                for (size_t j_1__ = 0; j_1__ < g_j_1_max__; ++j_1__) {
                    vars__.push_back(g(j_1__));
                }
                vars__.push_back(phi);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 83;
=======
            current_statement_begin__ = 70;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("k_p", "Tfor", Tfor);
            Eigen::Matrix<double, Eigen::Dynamic, 1> k_p(Tfor);
            stan::math::initialize(k_p, DUMMY_VAR__);
            stan::math::fill(k_p, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 84;
=======
            current_statement_begin__ = 71;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("k2_p", "Tfor", Tfor);
            Eigen::Matrix<double, Eigen::Dynamic, 1> k2_p(Tfor);
            stan::math::initialize(k2_p, DUMMY_VAR__);
            stan::math::fill(k2_p, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 85;
=======
            current_statement_begin__ = 72;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("g_p", "Tfor", Tfor);
            Eigen::Matrix<double, Eigen::Dynamic, 1> g_p(Tfor);
            stan::math::initialize(g_p, DUMMY_VAR__);
            stan::math::fill(g_p, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 86;
=======
            current_statement_begin__ = 73;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("gf", "(C + Tfor)", (C + Tfor));
            Eigen::Matrix<double, Eigen::Dynamic, 1> gf((C + Tfor));
            stan::math::initialize(gf, DUMMY_VAR__);
            stan::math::fill(gf, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 87;
=======
            current_statement_begin__ = 74;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("mufor", "L", L);
            Eigen::Matrix<double, Eigen::Dynamic, 1> mufor(L);
            stan::math::initialize(mufor, DUMMY_VAR__);
            stan::math::fill(mufor, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 88;
=======
            current_statement_begin__ = 75;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("log_lik", "(J * T)", (J * T));
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik((J * T));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 89;
=======
            current_statement_begin__ = 76;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            validate_non_negative_index("log_lik2", "(J * Tval)", (J * Tval));
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik2((J * Tval));
            stan::math::initialize(log_lik2, DUMMY_VAR__);
            stan::math::fill(log_lik2, DUMMY_VAR__);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 90;
=======
            current_statement_begin__ = 77;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            int pos;
            (void) pos;  // dummy to suppress unused var warning
            stan::math::fill(pos, std::numeric_limits<int>::min());
            stan::math::assign(pos,1);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 91;
=======
            current_statement_begin__ = 78;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            int pos2;
            (void) pos2;  // dummy to suppress unused var warning
            stan::math::fill(pos2, std::numeric_limits<int>::min());
            stan::math::assign(pos2,1);
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 92;
=======
            current_statement_begin__ = 79;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            int pos3;
            (void) pos3;  // dummy to suppress unused var warning
            stan::math::fill(pos3, std::numeric_limits<int>::min());
            stan::math::assign(pos3,1);
            // generated quantities statements
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 94;
=======
            current_statement_begin__ = 80;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(k_p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        (((get_base1(alpha, 1, "alpha", 1) + (get_base1(alpha, 2, "alpha", 1) * (T + 1))) + (get_base1(alpha, 3, "alpha", 1) * get_base1(k, T, "k", 1))) + (get_base1(sigma, 1, "sigma", 1) * normal_rng(0, 1, base_rng__))), 
                        "assigning variable k_p");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 95;
            for (int t = 2; t <= Tfor; ++t) {
                current_statement_begin__ = 95;
=======
            current_statement_begin__ = 81;
            for (int t = 2; t <= Tfor; ++t) {
                current_statement_begin__ = 81;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                stan::model::assign(k_p, 
                            stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list()), 
                            (((get_base1(alpha, 1, "alpha", 1) + (get_base1(alpha, 2, "alpha", 1) * (T + t))) + (get_base1(alpha, 3, "alpha", 1) * get_base1(k_p, (t - 1), "k_p", 1))) + (get_base1(sigma, 1, "sigma", 1) * normal_rng(0, 1, base_rng__))), 
                            "assigning variable k_p");
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 97;
=======
            current_statement_begin__ = 82;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(k2_p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        ((((get_base1(alpha2, 1, "alpha2", 1) + (get_base1(alpha2, 2, "alpha2", 1) * (T + 1))) + (get_base1(alpha2, 3, "alpha2", 1) * get_base1(k2, T, "k2", 1))) + (((rho * get_base1(sigma, 2, "sigma", 1)) / get_base1(sigma, 1, "sigma", 1)) * (get_base1(k_p, 1, "k_p", 1) - ((get_base1(alpha, 1, "alpha", 1) + (get_base1(alpha, 2, "alpha", 1) * (T + 1))) + (get_base1(alpha, 3, "alpha", 1) * get_base1(k, T, "k", 1)))))) + ((get_base1(sigma, 2, "sigma", 1) * stan::math::sqrt((1 - square(rho)))) * normal_rng(0, 1, base_rng__))), 
                        "assigning variable k2_p");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 98;
            for (int t = 2; t <= Tfor; ++t) {
                current_statement_begin__ = 98;
=======
            current_statement_begin__ = 83;
            for (int t = 2; t <= Tfor; ++t) {
                current_statement_begin__ = 83;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                stan::model::assign(k2_p, 
                            stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list()), 
                            ((((get_base1(alpha2, 1, "alpha2", 1) + (get_base1(alpha2, 2, "alpha2", 1) * (T + t))) + (get_base1(alpha2, 3, "alpha2", 1) * get_base1(k2_p, (t - 1), "k2_p", 1))) + (((rho * get_base1(sigma, 2, "sigma", 1)) / get_base1(sigma, 1, "sigma", 1)) * (get_base1(k_p, t, "k_p", 1) - ((get_base1(alpha, 1, "alpha", 1) + (get_base1(alpha, 2, "alpha", 1) * (T + t))) + (get_base1(alpha, 3, "alpha", 1) * get_base1(k_p, (t - 1), "k_p", 1)))))) + ((get_base1(sigma, 2, "sigma", 1) * stan::math::sqrt((1 - square(rho)))) * normal_rng(0, 1, base_rng__))), 
                            "assigning variable k2_p");
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 100;
=======
            current_statement_begin__ = 84;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g_p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        ((((psi + psi2) * get_base1(g, C, "g", 1)) - ((psi * psi2) * get_base1(g, (C - 1), "g", 1))) + (get_base1(sigma, 3, "sigma", 1) * normal_rng(0, 1, base_rng__))), 
                        "assigning variable g_p");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 101;
=======
            current_statement_begin__ = 85;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            stan::model::assign(g_p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        ((((psi + psi2) * get_base1(g_p, 1, "g_p", 1)) - ((psi * psi2) * get_base1(g, C, "g", 1))) + (get_base1(sigma, 3, "sigma", 1) * normal_rng(0, 1, base_rng__))), 
                        "assigning variable g_p");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 102;
            for (int t = 3; t <= Tfor; ++t) {
                current_statement_begin__ = 102;
=======
            current_statement_begin__ = 86;
            for (int t = 3; t <= Tfor; ++t) {
                current_statement_begin__ = 86;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                stan::model::assign(g_p, 
                            stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list()), 
                            ((((psi + psi2) * get_base1(g_p, (t - 1), "g_p", 1)) - ((psi * psi2) * get_base1(g_p, (t - 2), "g_p", 1))) + (get_base1(sigma, 3, "sigma", 1) * normal_rng(0, 1, base_rng__))), 
                            "assigning variable g_p");
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 103;
            stan::math::assign(gf, append_row(g, g_p));
            current_statement_begin__ = 105;
            if (as_bool(logical_eq(family, 0))) {
                current_statement_begin__ = 106;
                for (int t = 1; t <= Tfor; ++t) {
                    current_statement_begin__ = 106;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 107;
=======
            current_statement_begin__ = 87;
            stan::math::assign(gf, append_row(g, g_p));
            current_statement_begin__ = 89;
            if (as_bool(logical_eq(family, 0))) {
                current_statement_begin__ = 90;
                for (int t = 1; t <= Tfor; ++t) {
                    current_statement_begin__ = 90;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 91;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::model::assign(mufor, 
                                    stan::model::cons_list(stan::model::index_uni(pos), stan::model::nil_index_list()), 
                                    ((get_base1(k_p, t, "k_p", 1) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1)), 
                                    "assigning variable mufor");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                        current_statement_begin__ = 108;
                        stan::math::assign(pos, (pos + 1));
                    }
                }
                current_statement_begin__ = 110;
                stan::math::assign(mufor, stan::math::exp(mufor));
                current_statement_begin__ = 111;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 111;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 112;
=======
                        current_statement_begin__ = 92;
                        stan::math::assign(pos, (pos + 1));
                    }
                }
                current_statement_begin__ = 94;
                stan::math::assign(mufor, stan::math::exp(mufor));
                current_statement_begin__ = 95;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 95;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 96;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::model::assign(log_lik, 
                                    stan::model::cons_list(stan::model::index_uni(pos2), stan::model::nil_index_list()), 
                                    poisson_log_log(get_base1(d, pos2, "d", 1), (((get_base1(offset, pos2, "offset", 1) + get_base1(k, t, "k", 1)) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2, t, "k2", 1))) + get_base1(g, ((t - x) + J), "g", 1))), 
                                    "assigning variable log_lik");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                        current_statement_begin__ = 113;
                        stan::math::assign(pos2, (pos2 + 1));
                    }
                }
                current_statement_begin__ = 116;
                for (int t = 1; t <= Tval; ++t) {
                    current_statement_begin__ = 116;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 117;
=======
                        current_statement_begin__ = 97;
                        stan::math::assign(pos2, (pos2 + 1));
                    }
                }
                current_statement_begin__ = 100;
                for (int t = 1; t <= Tval; ++t) {
                    current_statement_begin__ = 100;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 101;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::model::assign(log_lik2, 
                                    stan::model::cons_list(stan::model::index_uni(pos3), stan::model::nil_index_list()), 
                                    poisson_log_log(get_base1(dval, pos3, "dval", 1), (((get_base1(offset2, pos3, "offset2", 1) + get_base1(k_p, t, "k_p", 1)) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1))), 
                                    "assigning variable log_lik2");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                        current_statement_begin__ = 118;
=======
                        current_statement_begin__ = 102;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::math::assign(pos3, (pos3 + 1));
                    }
                }
            } else if (as_bool(logical_gt(family, 0))) {
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                current_statement_begin__ = 122;
                for (int t = 1; t <= Tfor; ++t) {
                    current_statement_begin__ = 122;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 123;
                        if (as_bool(logical_gt(stan::math::fabs(((get_base1(k_p, t, "k_p", 1) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1))), 15))) {
                            current_statement_begin__ = 124;
                            stan::model::assign(mufor, 
                                        stan::model::cons_list(stan::model::index_uni(pos), stan::model::nil_index_list()), 
                                        0, 
                                        "assigning variable mufor");
                            current_statement_begin__ = 125;
                            stan::math::assign(pos, (pos + 1));
                        } else {
                            current_statement_begin__ = 127;
                            stan::model::assign(mufor, 
                                        stan::model::cons_list(stan::model::index_uni(pos), stan::model::nil_index_list()), 
                                        gamma_rng(phi, (phi / stan::math::exp(((get_base1(k_p, t, "k_p", 1) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1)))), base_rng__), 
                                        "assigning variable mufor");
                            current_statement_begin__ = 128;
                            stan::math::assign(pos, (pos + 1));
                        }
                    }
                }
                current_statement_begin__ = 131;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 131;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 132;
=======
                current_statement_begin__ = 106;
                for (int t = 1; t <= Tfor; ++t) {
                    current_statement_begin__ = 106;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 107;
                        stan::model::assign(mufor, 
                                    stan::model::cons_list(stan::model::index_uni(pos), stan::model::nil_index_list()), 
                                    gamma_rng(phi, (phi / stan::math::exp(((get_base1(k_p, t, "k_p", 1) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1)))), base_rng__), 
                                    "assigning variable mufor");
                        current_statement_begin__ = 108;
                        stan::math::assign(pos, (pos + 1));
                    }
                }
                current_statement_begin__ = 110;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 110;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 111;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::model::assign(log_lik, 
                                    stan::model::cons_list(stan::model::index_uni(pos2), stan::model::nil_index_list()), 
                                    neg_binomial_2_log_log(get_base1(d, pos2, "d", 1), (((get_base1(offset, pos2, "offset", 1) + get_base1(k, t, "k", 1)) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2, t, "k2", 1))) + get_base1(g, ((t - x) + J), "g", 1)), phi), 
                                    "assigning variable log_lik");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                        current_statement_begin__ = 133;
                        stan::math::assign(pos2, (pos2 + 1));
                    }
                }
                current_statement_begin__ = 136;
                for (int t = 1; t <= Tval; ++t) {
                    current_statement_begin__ = 136;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 137;
=======
                        current_statement_begin__ = 112;
                        stan::math::assign(pos2, (pos2 + 1));
                    }
                }
                current_statement_begin__ = 115;
                for (int t = 1; t <= Tval; ++t) {
                    current_statement_begin__ = 115;
                    for (int x = 1; x <= J; ++x) {
                        current_statement_begin__ = 116;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::model::assign(log_lik2, 
                                    stan::model::cons_list(stan::model::index_uni(pos3), stan::model::nil_index_list()), 
                                    neg_binomial_2_log_log(get_base1(dval, pos3, "dval", 1), (((get_base1(offset2, pos3, "offset2", 1) + get_base1(k_p, t, "k_p", 1)) + ((get_base1(age, x, "age", 1) - mean(age)) * get_base1(k2_p, t, "k2_p", 1))) + get_base1(gf, (((T + t) - x) + J), "gf", 1)), phi), 
                                    "assigning variable log_lik2");
<<<<<<< HEAD:src-i386/stanExports_M6model.h
                        current_statement_begin__ = 138;
=======
                        current_statement_begin__ = 117;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
                        stan::math::assign(pos3, (pos3 + 1));
                    }
                }
            }
            // validate, write generated quantities
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 83;
=======
            current_statement_begin__ = 70;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t k_p_j_1_max__ = Tfor;
            for (size_t j_1__ = 0; j_1__ < k_p_j_1_max__; ++j_1__) {
                vars__.push_back(k_p(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 84;
=======
            current_statement_begin__ = 71;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t k2_p_j_1_max__ = Tfor;
            for (size_t j_1__ = 0; j_1__ < k2_p_j_1_max__; ++j_1__) {
                vars__.push_back(k2_p(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 85;
=======
            current_statement_begin__ = 72;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t g_p_j_1_max__ = Tfor;
            for (size_t j_1__ = 0; j_1__ < g_p_j_1_max__; ++j_1__) {
                vars__.push_back(g_p(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 86;
=======
            current_statement_begin__ = 73;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t gf_j_1_max__ = (C + Tfor);
            for (size_t j_1__ = 0; j_1__ < gf_j_1_max__; ++j_1__) {
                vars__.push_back(gf(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 87;
=======
            current_statement_begin__ = 74;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t mufor_j_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < mufor_j_1_max__; ++j_1__) {
                vars__.push_back(mufor(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 88;
=======
            current_statement_begin__ = 75;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t log_lik_j_1_max__ = (J * T);
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 89;
=======
            current_statement_begin__ = 76;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            size_t log_lik2_j_1_max__ = (J * Tval);
            for (size_t j_1__ = 0; j_1__ < log_lik2_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik2(j_1__));
            }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
            current_statement_begin__ = 90;
            vars__.push_back(pos);
            current_statement_begin__ = 91;
            vars__.push_back(pos2);
            current_statement_begin__ = 92;
=======
            current_statement_begin__ = 77;
            vars__.push_back(pos);
            current_statement_begin__ = 78;
            vars__.push_back(pos2);
            current_statement_begin__ = 79;
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
            vars__.push_back(pos3);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
    static std::string model_name() {
=======
    std::string model_name() const {
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        return "model_M6model";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t aux_k_0_max__ = logical_gt(family, 0);
        for (size_t k_0__ = 0; k_0__ < aux_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        size_t alpha_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha2_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
=======
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha2";
        param_names__.push_back(param_name_stream__.str());
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        size_t sigma_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k2_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "psi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "psi2";
        param_names__.push_back(param_name_stream__.str());
        size_t gs_j_1_max__ = (C - 2);
        for (size_t j_1__ = 0; j_1__ < gs_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gs" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t g_j_1_max__ = C;
            for (size_t j_1__ = 0; j_1__ < g_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "g" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t k_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < k_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k2_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < k2_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k2_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t g_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < g_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "g_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gf_j_1_max__ = (C + Tfor);
        for (size_t j_1__ = 0; j_1__ < gf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mufor_j_1_max__ = L;
        for (size_t j_1__ = 0; j_1__ < mufor_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mufor" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = (J * T);
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik2_j_1_max__ = (J * Tval);
        for (size_t j_1__ = 0; j_1__ < log_lik2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos3";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t aux_k_0_max__ = logical_gt(family, 0);
        for (size_t k_0__ = 0; k_0__ < aux_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
<<<<<<< HEAD:src-i386/stanExports_M6model.h
        size_t alpha_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha2_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < alpha2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
=======
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha2";
        param_names__.push_back(param_name_stream__.str());
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
        size_t sigma_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k2_j_1_max__ = T;
        for (size_t j_1__ = 0; j_1__ < k2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "psi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "psi2";
        param_names__.push_back(param_name_stream__.str());
        size_t gs_j_1_max__ = (C - 2);
        for (size_t j_1__ = 0; j_1__ < gs_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gs" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t g_j_1_max__ = C;
            for (size_t j_1__ = 0; j_1__ < g_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "g" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t k_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < k_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t k2_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < k2_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "k2_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t g_p_j_1_max__ = Tfor;
        for (size_t j_1__ = 0; j_1__ < g_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "g_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gf_j_1_max__ = (C + Tfor);
        for (size_t j_1__ = 0; j_1__ < gf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mufor_j_1_max__ = L;
        for (size_t j_1__ = 0; j_1__ < mufor_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mufor" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = (J * T);
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik2_j_1_max__ = (J * Tval);
        for (size_t j_1__ = 0; j_1__ < log_lik2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pos3";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_M6model_namespace::model_M6model stan_model;
<<<<<<< HEAD:src-i386/stanExports_M6model.h
=======
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
>>>>>>> 29d36229bb3e961413905c03b5e6fe3d187d11c1:src/stanExports_M6model.h
#endif
