# script_simulation_study_section.r
# Pierre-Olivier Goffard pierre-olivier.goffard@univ-lyon1.fr
# This script reproduces the plot of the section 4 of the paper entitled Bayesian 
# model averaging for mortality forecasting using leave-future-out validation

# Libraries ----
library(StanMoMo)
library(tidyverse)
library(rstan)
library(bridgesampling)
library(parallel)
library(matrixcalc)
library(gridExtra)
library(extrafont)
windowsFonts()
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(scales)
library(stringr)

# Graphics hyperparameters ----
h_title <- 24 ; h_axis_text<-h_title -2; 
size_symbol <- 5; size_curve <- 2 ;  
h_ticks <- h_title-4; h_strip_text <-h_title-2

# Section 4.1 data generated by the APC model----
gen_model <- "apc"
weights_df <- read.csv(paste0("weights_df_",gen_model,".csv"))
mae_df <- read.csv(paste0("mae_df_",gen_model,".csv"))
apc_a_df <- read.csv("apc_a_df.csv")
apc_g_df <- read.csv("apc_g_df.csv")
apc_phi_df <- read.csv("apc_phi_df.csv")
apc_k_df <- read.csv("apc_k_df.csv")

## Posterior distribution of the APC generating model
a_plot <- ggplot(apc_a_df, aes(x = as.factor(x), y = a_x)) + 
  geom_boxplot() + 
  scale_x_discrete(breaks = apc_a_df$x[seq(1, length(unique(apc_a_df$x)), 5)]) + 
  labs(x = "Ages", y = "") + theme_bw(base_family='sans') +
  theme(
    axis.title = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title))
# ggsave(a_plot, filename = "../Figures/apc_a_plot.pdf")

k_plot <- ggplot(apc_k_df, aes(x = as.factor(t), y = k_t)) +
  geom_boxplot() +
  scale_x_discrete(breaks = apc_k_df$t[seq(1, length(unique(apc_k_df$t)), 10)]) + 
  labs(x = "Calendar years", y = "") + theme_bw(base_family='sans') +
  theme(
    axis.title = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title))
ggsave(k_plot, filename = "../Figures/apc_k_plot.pdf")

g_plot <- ggplot(apc_g_df, aes(x = as.factor(c), y = g_t_x)) + 
  geom_boxplot() +
  scale_x_discrete(breaks = apc_g_df$c[seq(1, length(unique(apc_g_df$c)), 15)]) + 
  labs(x = "Cohorts", y = "") + theme_bw(base_family='sans') +
  theme(
    axis.title = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title))
# ggsave(g_plot, filename = "../Figures/apc_g_plot.pdf")

phi_plot <- ggplot(apc_phi_df, aes(y = phi)) + geom_boxplot() +
  labs(x = "", y = "") + theme_bw(base_family='sans') +
  theme(
    axis.title = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    axis.text.x = element_blank(),
    plot.title = element_text(size = h_title))
# ggsave(phi_plot, filename = "../Figures/apc_phi_plot.pdf")

## Plot of the weights

weights_df_V1 <- weights_df%>%  pivot_longer(!c(sim, fitted_model, gen_model, n_years_val.x, n_years, n_years_val.y), names_to = "ensemble_method", values_to = "weight")
weights_df_V2 <- weights_df_V1 %>% group_by(n_years, n_years_val.x, ensemble_method, sim) %>% filter(weight==max(weight))
weights_df_V2$fitted_model <- as.factor(weights_df_V2$fitted_model)
weights_df_V3 <- weights_df_V2 %>% filter(n_years_val.x == 10) %>% group_by(ensemble_method, fitted_model, n_years) %>% summarize(prop = n() / 80, , .groups = 'keep') %>% mutate(fitted_model_up = str_to_upper(fitted_model))

weights_df_V3$ensemble_method <- as.factor(weights_df_V3$ensemble_method)
levels(weights_df_V3$ensemble_method) <- c("BMA", "Pseudo-BMA", "Stacking")
(g <- ggplot(data = weights_df_V3, aes(x = n_years, y = prop)) + 
    geom_point(aes(shape = as.factor(fitted_model_up)), size = size_symbol)  + 
    scale_shape_manual(values= 1:7) +
    facet_wrap(ensemble_method~., ncol = 1) + 
    scale_y_continuous(labels = scales::percent, breaks = c(0, 0.25, 0.5,0.75, 1), limits = c(0,1.2)) + 
    theme_bw(base_family='sans')) + 
  labs(x = "Number of calendar years in the training data set", y = "", shape = "Mortality models",  title = "Data generated by an APC model") +
  theme(
    axis.title = element_text(size = h_axis_text),
    plot.subtitle = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title), 
    strip.text.y = element_text(angle = 0), 
    strip.background = element_blank(), 
    legend.position  = "bottom",
    legend.text = element_text(size = h_axis_text ),
    legend.title = element_text(size = h_axis_text ),
    strip.text=element_text(size = h_strip_text, hjust=0,face = "italic")
  )

# ggsave(paste0("../Figures/weights_plot_",gen_model,".pdf" ))

## Plot of the MAE
df_mae_plot <- mae_df %>%  pivot_longer(!c(sim, gen_model, n_years_val, n_years), names_to = "model", values_to = "mae")  %>% filter(n_years_val == 10) %>% group_by(n_years, model)
# %>% summarize(mean_mae = median(mae)) 
model_shift <- data.frame(model = sort(unique(df_mae_plot$model)),
                          shift = -4:3 * 1
)
df_mae_plot_V1 <- df_mae_plot %>% left_join(model_shift, by = "model") %>% mutate(n_years_shifted = n_years + shift)

df_mae_plot_V1$model <- as.factor(df_mae_plot_V1$model)
levels(df_mae_plot_V1$model) <- c("APC","BMA","CBD", "LC", "M6","Pseudo-BMA", "RH","Stacking")
shape_palette <- c(1,15,2,3,4,16,5,17)

ggplot(data = df_mae_plot_V1) + 
  geom_point(mapping = aes(y=mae, x=n_years_shifted, shape = model), size = size_symbol) +
  scale_shape_manual(values= shape_palette) +
  scale_y_continuous(limits = c(0,max(df_mae_plot_V1$mae))) +
  theme_bw(base_family='sans') + 
  labs(x = "Number of calendar years in the training data set",
       y = "",
       title = "Data generated by an APC model", 
       subtitle = "Mean Absolute Error (in number of deaths)", 
       shape = "Mortality models") +
  theme(
    axis.title = element_text(size = h_axis_text),
    plot.subtitle = element_text(size = h_axis_text, face = "italic"),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title), 
    legend.position  = "bottom",
    legend.text = element_text(size = h_axis_text ),
    legend.title = element_text(size = h_axis_text ),
    
  )

# Section 4.2 Data generated by a mix between CBD and Renshaw-Haberman model----
gen_model <- "mix_cbd_rh"
weights_df <- read.csv(paste0("weights_df_",gen_model,".csv"))
mae_df <- read.csv(paste0("mae_df_",gen_model,".csv"))

## Plot of the weights
weights_df_V1 <- weights_df%>%  pivot_longer(!c(sim, fitted_model, gen_model, n_years_val.x, n_years, n_years_val.y), names_to = "ensemble_method", values_to = "weight")
weights_df_V2 <- weights_df_V1 %>% group_by(n_years, n_years_val.x, ensemble_method, sim) %>% filter(weight==max(weight))
weights_df_V2$fitted_model <- as.factor(weights_df_V2$fitted_model)
weights_df_V3 <- weights_df_V2 %>% filter(n_years_val.x == 10) %>% group_by(ensemble_method, fitted_model, n_years) %>% summarize(prop = n() / 80, , .groups = 'keep') %>% mutate(fitted_model_up = str_to_upper(fitted_model))

weights_df_V3$ensemble_method <- as.factor(weights_df_V3$ensemble_method)
levels(weights_df_V3$ensemble_method) <- c("BMA", "Pseudo-BMA", "Stacking")
(g <- ggplot(data = weights_df_V3, aes(x = n_years, y = prop)) + 
    geom_point(aes(shape = as.factor(fitted_model_up)), size = size_symbol)  + 
    scale_shape_manual(values= 1:7) +
    facet_wrap(ensemble_method~., ncol = 1) + 
    scale_y_continuous(labels = scales::percent, breaks = c(0, 0.25, 0.5,0.75, 1), limits = c(0,1.2)) + 
    theme_bw(base_family='sans')) + 
  labs(x = "Number of calendar years in the training data set", 
       y = "Proportion of times a model was chosen", 
       shape = "Mortality models",
       title = "Data generated by a CBD/RH model") +
  theme(
    axis.title = element_text(size = h_axis_text),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title), 
    strip.text.y = element_text(angle = 0), 
    strip.background = element_blank(), 
    legend.position  = "bottom",
    legend.text = element_text(size = h_axis_text ),
    legend.title = element_text(size = h_axis_text ),
    strip.text=element_text(size = h_strip_text, hjust=0, face = "italic")
  )

# ggsave(paste0("../Figures/weights_plot_",gen_model,".pdf" ))

## Plot of the MAE
df_mae_plot <- mae_df %>%  pivot_longer(!c(sim, gen_model, n_years_val, n_years), names_to = "model", values_to = "mae")  %>% filter(n_years_val == 10) %>% group_by(n_years, model) 
model_shift <- data.frame(model = sort(unique(df_mae_plot$model)),
                          shift = -4:3 * 1
)
df_mae_plot_V1 <- df_mae_plot %>% left_join(model_shift, by = "model") %>% mutate(n_years_shifted = n_years + shift)

df_mae_plot_V1$model <- as.factor(df_mae_plot_V1$model)
levels(df_mae_plot_V1$model) <- c("APC","BMA","CBD", "LC", "M6","Pseudo-BMA", "RH","Stacking")
shape_palette <- c(1,15,2,3,4,16,5,17)

ggplot(data = df_mae_plot_V1) + 
  geom_point(mapping = aes(y=mae, x=n_years_shifted, shape = model), size = size_symbol) +
  scale_y_continuous(limits = c(0, max(df_mae_plot_V1$mae))) + 
  scale_shape_manual(values= shape_palette) +
  theme_bw(base_family='sans') + 
  labs(x = "Number of calendar years in the training data set",
       y = "",
       title = "Data generated by a CBD/RH model",
       subtitle = "Mean Absolute Error (in number of deaths)", 
       shape = "Mortality models") +
  theme(
    axis.title = element_text(size = h_axis_text),
    plot.subtitle = element_text(size = h_axis_text, face = "italic"),
    axis.text = element_text(size = h_ticks),
    plot.title = element_text(size = h_title), 
    legend.position  = "bottom",
    legend.text = element_text(size = h_axis_text ),
    legend.title = element_text(size = h_axis_text ),
    
  )
# ggsave(paste0("../Figures/mae_plot_",gen_model,".pdf" ))

