// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4APCmodelfinal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4APCmodelfinalnb_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CBDmodelfinal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CBDmodelfinalnb_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4M6modelfinal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4M6modelfinalnb_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RHmodelfinal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RHmodelfinalnb_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4leecarterfinal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4leecarterfinalnb_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4APCmodelfinal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4APCmodelfinal_mod, 0},
    {"_rcpp_module_boot_stan_fit4APCmodelfinalnb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4APCmodelfinalnb_mod, 0},
    {"_rcpp_module_boot_stan_fit4CBDmodelfinal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CBDmodelfinal_mod, 0},
    {"_rcpp_module_boot_stan_fit4CBDmodelfinalnb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CBDmodelfinalnb_mod, 0},
    {"_rcpp_module_boot_stan_fit4M6modelfinal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4M6modelfinal_mod, 0},
    {"_rcpp_module_boot_stan_fit4M6modelfinalnb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4M6modelfinalnb_mod, 0},
    {"_rcpp_module_boot_stan_fit4RHmodelfinal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RHmodelfinal_mod, 0},
    {"_rcpp_module_boot_stan_fit4RHmodelfinalnb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RHmodelfinalnb_mod, 0},
    {"_rcpp_module_boot_stan_fit4leecarterfinal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4leecarterfinal_mod, 0},
    {"_rcpp_module_boot_stan_fit4leecarterfinalnb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4leecarterfinalnb_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_StanMoMo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
